### ISSUE TITLE
SQLite error on Missing Handler class

### ISSUE THREAD

**Issue by GuyWaguespack** [SynapseProject/synapse.core.net#1]
Issue when nonexistent handler class in YML file.  Causes SQLite error below: 

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Data.SQLite.SQLiteException: SQL logic error or missing database
near "Synapse": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Synapse.Core.DataAccessLayer.SynapseDal.ExecuteNonQuery(String sql, CommandBehavior commandBehavior) in C:\Users\guywa\Source\synapse.core.net\synapse.net\Synapse.Core\Dal\SynapseDal.cs:line 51
   at Synapse.Core.ActionItem.UpdateInstanceStatus(StatusType status, String message, Int32 sequence, Nullable`1 pid) in C:\Users\guywa\Source\synapse.core.net\synapse.net\Synapse.Core\Dal\ActionInstance.cs:line 99
   at Synapse.Core.DataAccessLayer.SynapseDal.UpdateActionInstance(Int64 instanceId, StatusType status, String message, Int32 sequence, Nullable`1 pid) in C:\Users\guywa\Source\synapse.core.net\synapse.net\Synapse.Core\Dal\SynapseDal.cs:line 67
   at Synapse.Core.Plan.rt_Progress(Object sender, HandlerProgressCancelEventArgs e) in C:\Users\guywa\Source\synapse.core.net\synapse.net\Synapse.Core\Runtime\PlanRuntime.cs:line 383
   at Synapse.Core.Plan.WriteUnhandledActionException(ActionItem a, Exception ex, Boolean writeProgress, Boolean writeLog) in C:\Users\guywa\Source\synapse.core.net\synapse.net\Synapse.Core\Runtime\PlanRuntime.cs:line 407
   at Synapse.Core.Plan.ExecuteHandlerProcessInProc(SecurityContext parentSecurityContext, ActionItem a, Dictionary`2 dynamicData, String parentExitData, Boolean dryRun) in C:\Users\guywa\Source\synapse.core.net\synapse.net\Synapse.Core\Runtime\PlanRuntime.cs:line 180
   at Synapse.Core.Plan.<>c__DisplayClass75_0.<ProcessRecursive>b__1(ActionItem a) in C:\Users\guywa\Source\synapse.core.net\synapse.net\Synapse.Core\Runtime\PlanRuntime.cs:line 138
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Synapse.Core.Plan.ProcessRecursive(SecurityContext parentSecurityContext, ActionItem actionGroup, List`1 actions, ExecuteResult result, Dictionary`2 dynamicData, Boolean dryRun, Func`6 executeHandlerMethod) in C:\Users\guywa\Source\synapse.core.net\synapse.net\Synapse.Core\Runtime\PlanRuntime.cs:line 136
   at Synapse.Core.Plan.Start(Dictionary`2 dynamicData, Boolean dryRun, Boolean inProc) in C:\Users\guywa\Source\synapse.core.net\synapse.net\Synapse.Core\Runtime\PlanRuntime.cs:line 99
   at Synapse.cli.Program.<>c__DisplayClass1_0.<Main>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Synapse.cli.Program.Main(String[] args)

**Comment by steveshortt** [comment]
@GuyWaguespack: this is fixed in [commit ccb92a7](https://github.com/SynapseProject/synapse.core.net/commit/ccb92a7830ff20860eeffb5c4300abc57c5546df).

Line 91 of \Synapse.Core\Dal\ActionInstance.cs
`,{Fields.StatusMsg} = '{message.Replace( "'", "```" )}'`
